highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Mahalete Haile's Resume
name: Mahalete Haile
email: mahialemu@gmail.com
email_full: mailto:mahialemu@gmail.com
website: github.io/sustain
website_full: https://jekyller.github.io/sustain
github: trending
twitter: twitter
tel: +358 442750255

google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address:
  street: klaneettitie 1 A, 24
  postcode: 00420
  city: Helsinki
  country: Finland


# needed for travis-ci build
exclude: [vendor]

theme: jekyll-theme-cayman